In [1]:
import os
import random
import shutil
import pandas as pd
import json

In [9]:
data = pd.read_csv('train.csv')
data.shape

(7357, 63)

In [7]:
data.head()

,Unnamed: 0,:authority,:method,:path,:scheme,accept,accept-encoding,accept-language,adrum,body,...,x-skyscanner-viewid,x-youtube-ad-signals,x-youtube-client-name,x-youtube-client-version,x-youtube-device,x-youtube-page-cl,x-youtube-page-label,x-youtube-time-zone,x-youtube-utc-offset,x-youtube-variants-checksum
0,0,NaN,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","gzip, deflate, br","ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",NaN,state12345=MTg%3D+\n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,state12345=MzQ%3D+\n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","gzip, deflate, br","ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",NaN,state12345=MjY%3D+\n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,state12345=MjE%3D+\n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,"text/html,application/xhtml+xml,application/xm...","gzip, deflate, br","ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",NaN,state12345=MzU%3D+\n,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data.describe()

,Unnamed: 0,content-length,dst_port,google-accounts-xsrf,protocol,src_port,upgrade-insecure-requests,uri_fragment,uri_password,uri_port,uri_username,x-same-domain,x-youtube-client-name,x-youtube-page-cl,x-youtube-utc-offset
count,7357.000000,2686.000000,7357.0,4.0,7.357000e+03,7357.0,39.0,0.0,0.0,7357.000000,0.0,4.0,245.0,245.0,245.0
mean,3678.000000,3130.495905,80.0,1.0,1.100000e+00,44332.0,1.0,NaN,NaN,0.098410,NaN,1.0,1.0,304735510.0,180.0
std,2123.927298,4605.620732,0.0,0.0,1.472256e-13,0.0,0.0,NaN,NaN,94.213845,NaN,0.0,0.0,0.0,0.0
min,0.000000,0.000000,80.0,1.0,1.100000e+00,44332.0,1.0,NaN,NaN,-1.000000,NaN,1.0,1.0,304735510.0,180.0
25%,1839.000000,351.000000,80.0,1.0,1.100000e+00,44332.0,1.0,NaN,NaN,-1.000000,NaN,1.0,1.0,304735510.0,180.0
50%,3678.000000,1756.000000,80.0,1.0,1.100000e+00,44332.0,1.0,NaN,NaN,-1.000000,NaN,1.0,1.0,304735510.0,180.0
75%,5517.000000,3472.500000,80.0,1.0,1.100000e+00,44332.0,1.0,NaN,NaN,-1.000000,NaN,1.0,1.0,304735510.0,180.0
max,7356.000000,38949.000000,80.0,1.0,1.100000e+00,44332.0,1.0,NaN,NaN,8080.000000,NaN,1.0,1.0,304735510.0,180.0